version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Installing grails
      - curl -L https://github.com/grails/grails-core/releases/download/v2.5.6/grails-2.5.6.zip -o /grails.zip
      - unzip /grails.zip -d /opt
      - ENV GRAILS_HOME /opt/grails-2.5.6
      - ENV PATH $GRAILS_HOME/bin:$PATH
  build:
    commands:
      - echo Build started on `date`
      - grails war
      - docker build -t $APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME .
      - docker tag $APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME
      - printf '[{"name":"%s","imageUri":"%s"}]' $APPLICATION_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$DEPLOYMENT_GROUP_NAME > taskdefinition.json 
artifacts:
  files: taskdefinition.json